project:
  type: website
website:
  title: "HowToGreek"
  page-navigation: true
  repo-url: https://github.com/vrallis/HowToGreek
  repo-actions: [edit, issue]
  open-graph:
    locale: el_GR
    site-name: "How To Greek"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: Tutorials
        file: tutorials/index.qmd

  page-footer:
    left: "Αυτό το περιεχόμενο είναι ανοικτού κώδικα<br>Άδεια χρήσης υπό την [{{< fa regular copyright >}} GPL-3.0](https://www.gnu.org/licenses/gpl-3.0.en.html)"
    right: "Από τον Βασίλειο Ράλλη<br>Φτιαγμένο με {{< fa solid heart >}} και [{{< fa brands python >}}](https://www.python.org/)"
    background: light
    border: true

format:
  html:
    # grid: 
    #   body-width: 900px
    toc: true
    code-link: true
    anchor-sections: false
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
    fontsize: 1.3em
    number-sections: true
    theme:
      light: flatly
      dark: darkly
    includes:
      in_header: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
        <style>
        body {
        font-family: 'Roboto', sans-serif;
          }
        </style>