project:
  type: website

website:
  title: "HowToGreek"
  open-graph:
    locale: el_GR
    site-name: "How To Greek"
  navbar:
    background: primary
    style: docked
    search: true
    left:
      - href: index.qmd
        text: Αρχική
    right:
      - about.qmd
  page-footer:
    left: "Αυτό το περιεχόμενο είναι ανοικτού κώδικα<br>Άδεια χρήσης υπό την [{{< fa regular copyright >}} GPL-3.0](https://www.gnu.org/licenses/gpl-3.0.en.html)"
    right: "Από τον Βασίλειο Ράλλη<br>Φτιαγμένο με {{< fa solid heart >}} και [{{< fa brands python >}}](https://www.python.org/)"
    background: light
    border: true

format:
  html:
    grid: 
      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
    fontsize: 1.3em
    theme:
      light: flatly
      dark: darkly
    includes:
      in_header: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />